"""add player2_id to game_events

Revision ID: d1a9ec1b04e5
Revises: 03f611a985be
Create Date: 2026-08-17 20:34:09.905523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a9ec1b04e5'
down_revision: Union[str, None] = '03f611a985be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_events', sa.Column('player2_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game_events', 'players', ['player2_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_events', type_='foreignkey')
    op.drop_column('game_events', 'player2_id')
    # ### end Alembic commands ###
