"""initial schema

Revision ID: 92d8ed6b0d55
Revises: 0d0604022985
Create Date: 2026-08-04 23:00:46.147947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "92d8ed6b0d55"
down_revision: Union[str, None] = "0d0604022985"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uid", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("home_team_color", sa.String(length=7), nullable=False),
        sa.Column("away_team_color", sa.String(length=7), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "done", "failed", name="gamestatus"),
            nullable=False,
        ),
        sa.Column("stats_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uid"),
    )
    op.drop_table("videos")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("uid", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("file_path", sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
        sa.Column("home_team_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("away_team_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("pending", "processing", "done", "failed", name="videostatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "stats_json", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"], ["teams.id"], name=op.f("videos_away_team_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"], ["teams.id"], name=op.f("videos_home_team_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("videos_pkey")),
        sa.UniqueConstraint(
            "uid",
            name=op.f("videos_uid_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("games")
    # ### end Alembic commands ###
