"""structured stats tables

Revision ID: f27ad58b88d6
Revises: 92d8ed6b0d55
Create Date: 2026-08-04 23:20:11.281883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f27ad58b88d6"
down_revision: Union[str, None] = "92d8ed6b0d55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("frame", sa.Integer(), nullable=False),
        sa.Column("timestamp_sec", sa.Float(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_player_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("jersey_number", sa.Integer(), nullable=True),
        sa.Column("distance_covered_m", sa.Float(), nullable=False),
        sa.Column("shot_attempts", sa.Integer(), nullable=False),
        sa.Column("shot_makes", sa.Integer(), nullable=False),
        sa.Column("passes_made", sa.Integer(), nullable=False),
        sa.Column("passes_received", sa.Integer(), nullable=False),
        sa.Column("possession_frames", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_team_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("possession_pct", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "games", sa.Column("duration_seconds", sa.Float(), server_default="0", nullable=False)
    )
    op.add_column("games", sa.Column("fps", sa.Float(), server_default="0", nullable=False))
    op.drop_column("games", "stats_json")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column(
            "stats_json", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("games", "fps")
    op.drop_column("games", "duration_seconds")
    op.drop_table("game_team_stats")
    op.drop_table("game_player_stats")
    op.drop_table("game_events")
    # ### end Alembic commands ###
